{% set name = "slackclient" %}
{% set version = "2.1.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "eeb0dad774f6661f7504d80d8a22deadadb941b840e7a0719b5b92d4d84f9015" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python >=3.6,<4.0a0
    - aiohttp >3.5.2

test:
  imports:
    - slackclient

about:
  home: https://github.com/slackhq/python-slackclient
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Python client for Slack.com'
  dev_url: https://github.com/slackhq/python-slackclient
  doc_url: https://slackapi.github.io/python-slackclient/

extra:
  recipe-maintainers:
    - pmlandwehr
