{% set name = "slackclient" %}
{% set version = "2.9.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slackclient-{{ version }}.tar.gz
  sha256: ab79fefb5412d0595bc01d2f195a787597f2a617b6766562932ab9ffbe5cb173

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aiohttp >3.5.2,<4.0.0

test:
  imports:
    - slack
    - slack.rtm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/slackhq/python-slackclient
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python client for Slack.com
  doc_url: https://slackapi.github.io/python-slackclient/
  dev_url: https://github.com/slackhq/python-slackclient

extra:
  recipe-maintainers:
    - pmlandwehr
    - CurtLH
