{% set name = "slackclient" %}
{% set version = "2.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "3f9da5b111b8c4944380674d193c3ffd5bd4a36cda8b58fb2404f900afb0b1fa" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - websocket-client >=0.35,<1.0a0
    - requests >=2.11,<3.0a0
    - six >=1.10,<2.0a0

test:
  imports:
    - slackclient

about:
  home: https://github.com/slackhq/python-slackclient
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Python client for Slack.com'
  dev_url: https://github.com/slackhq/python-slackclient
  doc_url: https://slackapi.github.io/python-slackclient/

extra:
  recipe-maintainers:
    - pmlandwehr
